//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insumos()
        {
            this.Insumos_OrdenPedido = new HashSet<Insumos_OrdenPedido>();
            this.Producto = new HashSet<Producto>();
        }
    
        public int id_insumos { get; set; }
        public int id_categoria_insumos { get; set; }
        public string rut_proveedor_insumos { get; set; }
        public System.DateTime fecha_venc_insumos { get; set; }
        public string descrip_insumos { get; set; }
        public string stock_insumos { get; set; }
    
        public virtual Categoria_Insumos Categoria_Insumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insumos_OrdenPedido> Insumos_OrdenPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
