//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden_Pedidos()
        {
            this.Insumos_OrdenPedido = new HashSet<Insumos_OrdenPedido>();
        }
    
        public int id_ordenPedido { get; set; }
        public string rut_proveedor { get; set; }
        public string numero_oPedido { get; set; }
        public string cantidad_ordenPedido { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_actualizada { get; set; }
        public string status_ordenPedido { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insumos_OrdenPedido> Insumos_OrdenPedido { get; set; }
    }
}
