//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id_agenda { get; set; }
        public string status_reserva { get; set; }
        public System.DateTime horario_reserva { get; set; }
    
        public virtual Agenda Agenda { get; set; }
    }
}
