//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Clinica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Agenda = new HashSet<Agenda>();
        }

        public string run_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string apellidoP_usuario { get; set; }
        public string apellidoM_usuario { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime fecha_nac_usuario { get; set; }
        public string usuario1 { get; set; }
        [DataType(DataType.Password)]
        public string password_usuario { get; set; }
        [DataType(DataType.Password)]
        [Compare("password_usuario", ErrorMessage = "Las contraseñas no son iguales")]
        public string confir_password_usuario { get; set; }
        public string direccion_usuario { get; set; }
        public int region_usuario { get; set; }
        public int comuna_usuario { get; set; }
        [EmailAddress]
        public string email_usuario { get; set; }
        public string fono_usuario { get; set; }
        public int idTipo_usuario { get; set; }
        public Nullable<int> idCliente_usuario { get; set; }
        public string persona_cargo { get; set; }
        public string status_usuario { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime fecha_creacion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Comuna Comuna { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
        public virtual Region Region { get; set; }
    }
}
